DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS pedido;

CREATE TABLE usuario (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT UNIQUE NOT NULL,
  senha TEXT NOT NULL
);

CREATE TABLE pedido (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  semestre INTEGER NOT NULL,
  descricao TEXT NOT NULL,
  total INT NOT NULL
);